language: c

script:
  - clang -coverage -O0 main.c -o main
  - ./plover
  - gcov main.c
  
env:
  global:
    - CODECOV_TOKEN="6a50fc10-c235-45c9-9104-dd165635ae8e
after_success:
- bash <(curl -s https://codecov.io/bash)
